### ISSUE TITLE
PagerDuty integration

### ISSUE THREAD

**Issue by dshack** [intercom/banjaxed#37]
It would be really cool if PagerDuty incidents could automatically open banjaxed incidents.

This could be implemented with PagerDuty [service-level webhooks](https://support.pagerduty.com/hc/en-us/articles/202829320-Using-Webhooks-to-Email-Notifications-when-Incidents-Trigger-Acknowledge-Resolve), and would allow only certain services (say, high-sev ones) to open these incidents.

MVP: PagerDuty webhook opens new Banjaxed incident

Nice-to-haves:
* If a user exists in both tools, an acknowledgement in PagerDuty assigns it to that user in banjaxed.
* If a PagerDuty incident is resolved, the banjaxed incident closes.
* If a comment is entered in banjaxed, it is [posted to the PagerDuty incident as a note](https://developer.pagerduty.com/documentation/rest/incidents/notes/create).

**Comment by eugeneius** [comment]
@vegetableman implemented this in #48 :tada:

**Comment by vegetableman** [comment]
@chrisgagne have submitted a bounty claim. Let me know if you did not receive it.

**Comment by dshack** [comment]
Nice!
